import {
  BeforeInsert,
  Column,
  Entity,
  JoinColumn,
  OneToMany,
  OneToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { ApiProperty } from '@nestjs/swagger';
import { hash } from 'bcrypt';
import { ExerciseEntity } from '@/exercise/exercise.entity';
import { GroupEntity } from '@/group/group.entity';
import { TemplateEntity } from '@/template/template.entity';
import { SetEntity } from '@/set/set.entity';
import { TrainingEntity } from '@/training/training.entity';
import { MonitorEntity } from '@/monitor/monitor.entity';

@Entity({ name: 'users' })
export class UserEntity {
  @ApiProperty({
    example: '27ed-6f79-40b1-aa4b-d24f',
    description: 'The autogenerated unique identifier.',
  })
  @PrimaryGeneratedColumn('uuid')
  ID: string;

  @ApiProperty({
    example: 'alex@shepel.com',
    description: "User's email. It will be used for the account activation.",
  })
  @Column({
    unique: true,
  })
  Email: string;

  @ApiProperty({
    example: 1,
    description: "User's name. It will be displayed as nickname inside the app.",
  })
  @Column({
    nullable: true,
  })
  Name: string;

  @ApiProperty({
    example: '31415',
    description: 'The password.',
  })
  @Column({
    select: false,
  })
  Password: string;

  @ApiProperty({
    example: 'Tue Jan 17 2023 10:28:35 GMT+0200',
    description:
      'The date of the last success logout operation. It could be used for token validation.',
  })
  @Column({
    type: 'timestamptz',
    default: () => 'CURRENT_TIMESTAMP',
  })
  LastLogoutDate: Date;

  @BeforeInsert()
  async hashPassword() {
    this.Password = await hash(this.Password, Number(process.env.SALT));
  }

  @OneToMany(() => ExerciseEntity, exercise => exercise.User)
  Exercises: ExerciseEntity[];

  @OneToMany(() => GroupEntity, group => group.User)
  Groups: GroupEntity[];

  @OneToMany(() => GroupEntity, template => template.User)
  Templates: TemplateEntity[];

  @OneToMany(() => SetEntity, set => set.User)
  Sets: SetEntity[];

  @OneToMany(() => TrainingEntity, training => training.User)
  Trainings: TrainingEntity[];

  @OneToOne(() => MonitorEntity, monitor => monitor.User)
  @JoinColumn()
  Monitor: MonitorEntity;
}
